//------------------------------------------------------------------------------
// <auto-generated>
//     Ce fichier est genere automatiquement par ASP.NET.
//     Ne pas modifier manuellement.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCYemba
{

    public partial class AvantTest
    {

        protected global::System.Web.UI.WebControls.Literal litTitreTest;
        protected global::System.Web.UI.WebControls.Literal litNbQ;
        protected global::System.Web.UI.WebControls.Literal litDuree;
        protected global::System.Web.UI.WebControls.Literal litNbSections;
        protected global::System.Web.UI.WebControls.Literal litChips;
        protected global::System.Web.UI.WebControls.Button btnLancer;

    }

}