//------------------------------------------------------------------------------
// <auto-generated>
//     Ce fichier est genere automatiquement par ASP.NET.
//     Ne pas modifier manuellement.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCYemba
{

    public partial class Certificat
    {

        protected global::System.Web.UI.WebControls.Literal litNomCandidat;
        protected global::System.Web.UI.WebControls.Literal litTypeTestCert;
        protected global::System.Web.UI.WebControls.Literal litDateCert;
        protected global::System.Web.UI.WebControls.Literal litDateFooter;
        protected global::System.Web.UI.WebControls.Literal litScoreCert;
        protected global::System.Web.UI.WebControls.Literal litScoreLCert;
        protected global::System.Web.UI.WebControls.Literal litScoreSCert;
        protected global::System.Web.UI.WebControls.Literal litScoreRCert;
        protected global::System.Web.UI.WebControls.Literal litNiveauCert;
        protected global::System.Web.UI.WebControls.Literal litIdCert;
        protected global::System.Web.UI.WebControls.Panel pnlNiveauCert;
        protected global::System.Web.UI.WebControls.Panel pnlScoreL;
        protected global::System.Web.UI.WebControls.Panel pnlScoreS;
        protected global::System.Web.UI.WebControls.Panel pnlScoreR;

    }

}