//------------------------------------------------------------------------------
// <auto-generated> Ne pas modifier. </auto-generated>
//------------------------------------------------------------------------------
namespace TLCYemba
{
    public partial class ChoixTest
    {
        protected global::System.Web.UI.WebControls.Panel       pnlConnecte;
        protected global::System.Web.UI.WebControls.Panel       pnlDeconnecte;
        protected global::System.Web.UI.WebControls.Literal     litNavInitiale;
        protected global::System.Web.UI.WebControls.Literal     litNavNom;
        protected global::System.Web.UI.WebControls.Panel       pnlErreur;
        protected global::System.Web.UI.WebControls.Literal     litErreur;
        protected global::System.Web.UI.WebControls.HiddenField hfTypeTest;
        protected global::System.Web.UI.WebControls.Button      btnCommencer;
    }
}
