//------------------------------------------------------------------------------
// <auto-generated> Ne pas modifier. </auto-generated>
//------------------------------------------------------------------------------

namespace TLCYemba
{
    public partial class Connexion
    {

        protected global::System.Web.UI.WebControls.Panel pnlSucces;
        protected global::System.Web.UI.WebControls.Panel pnlReset;
        protected global::System.Web.UI.WebControls.Panel pnlErreur;
        protected global::System.Web.UI.WebControls.Literal litErreur;
        protected global::System.Web.UI.WebControls.HyperLink lnkGoogle;
        protected global::System.Web.UI.WebControls.HyperLink lnkGitHub;
        protected global::System.Web.UI.WebControls.HyperLink lnkApple;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtMdp;
        protected global::System.Web.UI.WebControls.Button btnConnecter;
        protected global::System.Web.UI.WebControls.Button btnInvite;

    }

}