//------------------------------------------------------------------------------
// <auto-generated>
//     Ce fichier est genere automatiquement par ASP.NET.
//     Ne pas modifier manuellement.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCYemba
{

    public partial class Dashboard
    {

        protected global::System.Web.UI.WebControls.Literal litInitiale;
        protected global::System.Web.UI.WebControls.Literal litNomNav;
        protected global::System.Web.UI.WebControls.Literal litPrenom;
        protected global::System.Web.UI.WebControls.Literal litNbTests;
        protected global::System.Web.UI.WebControls.Literal litMeilleurScore;
        protected global::System.Web.UI.WebControls.Literal litScoreMoyen;
        protected global::System.Web.UI.WebControls.Literal litNiveau;
        protected global::System.Web.UI.WebControls.Literal litDernierScore;
        protected global::System.Web.UI.WebControls.Literal litDernierNiveau;
        protected global::System.Web.UI.WebControls.Literal litDernierType;
        protected global::System.Web.UI.WebControls.Literal litDernierDate;
        protected global::System.Web.UI.WebControls.Panel pnlDernierScore;
        protected global::System.Web.UI.WebControls.Panel pnlPasDeScore;
        protected global::System.Web.UI.WebControls.Button btnDeconnecter;

    }

}