//------------------------------------------------------------------------------
// <auto-generated> Ne pas modifier. </auto-generated>
//------------------------------------------------------------------------------

namespace TLCYemba
{
    public partial class Inscription
    {

        protected global::System.Web.UI.WebControls.Panel pnlErreur;
        protected global::System.Web.UI.WebControls.Literal litErreur;
        protected global::System.Web.UI.WebControls.TextBox txtNom;
        protected global::System.Web.UI.WebControls.TextBox txtPrenom;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtMdp;
        protected global::System.Web.UI.WebControls.TextBox txtMdpConfirm;
        protected global::System.Web.UI.WebControls.Button btnInscrire;

    }

}