//------------------------------------------------------------------------------
// <auto-generated>
//     Ce fichier est genere automatiquement par ASP.NET.
//     Ne pas modifier manuellement.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCYemba
{

    public partial class Leaderboard
    {

        protected global::System.Web.UI.WebControls.Panel pnlPodium;
        protected global::System.Web.UI.WebControls.Literal litPodium;
        protected global::System.Web.UI.WebControls.Repeater rptLeaderboard;

    }

}