//------------------------------------------------------------------------------
// <auto-generated>
//     Ce fichier est genere automatiquement par ASP.NET.
//     Ne pas modifier manuellement.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCYemba
{

    public partial class MotDePasseOublie
    {

        protected global::System.Web.UI.WebControls.Panel pnlSucces;
        protected global::System.Web.UI.WebControls.Panel pnlErreur;
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        protected global::System.Web.UI.WebControls.Panel pnlSuite;
        protected global::System.Web.UI.WebControls.Literal litErreur;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.Button btnEnvoyer;
        protected global::System.Web.UI.WebControls.Button btnVersCode;

    }

}