//------------------------------------------------------------------------------
// <auto-generated>
//     Ce fichier est genere automatiquement par ASP.NET.
//     Ne pas modifier manuellement.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCYemba
{

    public partial class Resultat
    {

        protected global::System.Web.UI.WebControls.Literal litScoreTotal;
        protected global::System.Web.UI.WebControls.Literal litNiveau;
        protected global::System.Web.UI.WebControls.Literal litPourcentage;
        protected global::System.Web.UI.WebControls.Literal litTypeTest;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.Literal litDate;
        protected global::System.Web.UI.WebControls.Literal litScoreL;
        protected global::System.Web.UI.WebControls.Literal litBrutL;
        protected global::System.Web.UI.WebControls.Literal litScoreS;
        protected global::System.Web.UI.WebControls.Literal litBrutS;
        protected global::System.Web.UI.WebControls.Literal litScoreR;
        protected global::System.Web.UI.WebControls.Literal litBrutR;
        protected global::System.Web.UI.WebControls.Panel pnlNiveauBadge;
        protected global::System.Web.UI.WebControls.Panel progressGlobal;
        protected global::System.Web.UI.WebControls.Panel progressL;
        protected global::System.Web.UI.WebControls.Panel progressS;
        protected global::System.Web.UI.WebControls.Panel progressR;
        protected global::System.Web.UI.WebControls.Button btnNouveauTest;
        protected global::System.Web.UI.WebControls.Button btnVoirHistorique;

    }

}