//------------------------------------------------------------------------------
// <auto-generated>
//     Ce fichier est genere automatiquement par ASP.NET.
//     Ne pas modifier manuellement.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCYemba
{

    public partial class VerificationCode
    {

        protected global::System.Web.UI.WebControls.Panel pnlErreur;
        protected global::System.Web.UI.WebControls.Literal litErreur;
        protected global::System.Web.UI.WebControls.Literal litEmail;
        protected global::System.Web.UI.WebControls.HiddenField hfCode;
        protected global::System.Web.UI.WebControls.Button btnVerifier;
        protected global::System.Web.UI.WebControls.LinkButton lbRenvoyer;

    }

}